language: php
php:
  - '7.0'
  - '7.1'
install:
  - composer validate
  - composer install --no-interaction
addons:
  code_climate:
    repo_token: b234ae520288cdd86449188ee9b0bb312d9afb357830c3439437041aa3123012
after_success:
  - vendor/bin/test-reporter
